### ISSUE TITLE
Error adding censys api id and secret

### ISSUE THREAD

**Issue by Crtc4L** [christophetd/censys-subdomain-finder#9]
Upon adding censys-api-id and censys-api-secret

this is the result after i input the censys api id 

error : too few arguments. 

Please fix this error.

**Comment by christophetd** [comment]
Can you post the exact commands you ran?

**Comment by Crtc4L** [comment]
python censys_subdomain_finder.py --censys-api-id <censys api id here>

**Comment by Crtc4L** [comment]
ok. i will try this out and get back to you if this will work or not.

**Comment by Crtc4L** [comment]
as i try that method. It worked. Thank you for clarifying this out.

**Comment by krivadna** [comment]
How to install censys subdomain finder

**Comment by krivadna** [comment]
NOT WORKING

python cloudflair.py myvulnerable.site --cloudfront
[*] Retrieving Cloudflare IP ranges from https://www.cloudflare.com/ips-v4
Traceback (most recent call last):
  File "/data/data/com.termux/files/home/CloudFlair/cloudflair.py", line 213, in <module>
    main(args.domain, args.output_file, censys_api_id, censys_api_secret, args.use_cloudfront)
  File "/data/data/com.termux/files/home/CloudFlair/cloudflair.py", line 182, in main
    hosts = find_hosts(domain, censys_api_id, censys_api_secret, use_cloudfront)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/home/CloudFlair/cloudflair.py", line 45, in find_hosts
    if not dns_utils.is_valid_domain(domain):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/home/CloudFlair/dns_utils.py", line 5, in is_valid_domain
    dns.resolver.query(domain, 'A')
  File "/data/data/com.termux/files/home/CloudFlair/venv38/lib/python3.11/site-packages/dns/resolver.py", line 1131, in query
    return get_default_resolver().query(qname, rdtype, rdclass, tcp, source,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/home/CloudFlair/venv38/lib/python3.11/site-packages/dns/resolver.py", line 1041, in query
    timeout = self._compute_timeout(start)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/home/CloudFlair/venv38/lib/python3.11/site-packages/dns/resolver.py", line 858, in _compute_timeout
    raise Timeout(timeout=duration)
dns.exception.Timeout: The DNS operation timed out after 30.002615451812744 seconds
